//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSChina2020AppComp02.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Previos_Competition
    {
        public int OrdinalNo { get; set; }
        public Nullable<int> Year { get; set; }
        public string City_and_Country { get; set; }
        public Nullable<int> MemberNumber { get; set; }
    }
}
