//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSChina2020AppComp02.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedMark
    {
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public double PositionX { get; set; }
        public double PositionY { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
