//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSChina2020AppComp02.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SponsorClassName
    {
        public int ID { get; set; }
        public int SponsorID { get; set; }
        public int CategoryID { get; set; }
        public int CompetitionID { get; set; }
        public double Amount { get; set; }
        public int CompetenceID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Competence Competence { get; set; }
        public virtual Competition Competition { get; set; }
        public virtual Sponsor Sponsor { get; set; }
    }
}
